I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 394, in script
    return opening_questions
  File "game/script.rpy", line 394, in <module>
    return opening_questions
NameError: name 'opening_questions' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 394, in script
    return opening_questions
  File "C:\Users\Emily Lin\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 1485, in execute
    renpy.store._return = renpy.python.py_eval(self.expression)
  File "C:\Users\Emily Lin\Downloads\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Emily Lin\Downloads\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 394, in <module>
    return opening_questions
NameError: name 'opening_questions' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
Forever Yours, The Devil 1.0
Sat Jan 18 21:57:39 2025
